### ISSUE TITLE
Tidy up routes

### ISSUE THREAD

**Issue by americodls** [unfazedEgnimadevspace/Gracker#24]
The routes file should be organized in two namespaces "app" and "website".
The user routes from the devise should live under the "app" namespace.

**Comment by unfazedEgnimadevspace** [comment]
![bug](https://github.com/unfazedEgnimadevspace/Gracker/assets/96634477/93df11ba-539c-47ce-9128-c5e73c32f538)

Hello @americodls  

I started tidying up the routes and I keep getting this bug,  i think it is because the devise controllers are not in the app directory and i can't seem to find where they are , can you help me out.

Thanks
