### ISSUE TITLE
Exercise gifs not loading anymore

### ISSUE THREAD

**Issue by unfazedEgnimadevspace** [unfazedEgnimadevspace/Gracker#31]
Hello @americodls 

I think the website where we were getting exercise training gifs is no longer responding.

What should we do about this?

**Comment by americodls** [comment]
Yep, I saw that too...

I found the source from where I got that JSON, now they changed the links, and it seems they added limits of requests for the gifs:
https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb/

I wrote a script and downloaded all the gifs. We could host somewhere later.
You can download them here:
https://drive.google.com/file/d/1ddiAwrDGzoFJ0JsOZPaMxAeFb7MSAo2r/view?usp=sharing

We should not add them to the git repository I think, usually, we don't do that in professional projects. Git is not good with binary files. And it would make the repository slow for download...

**Comment by americodls** [comment]
@unfazedEgnimadevspace 

It's not uncommon to see in professional projects the use of CDN services to serve all assets or static files like images, videos, JS, CSS, and HTML. Those services provide a lot of performance optimizations.

Since we are not deploying it to production (yet!), I don't think we should think if we will use a CDN or serve the static files from our webserver directly.

However, we can make the gifs be displayed to us in development while preparing the application for any solution we would choose in production.

I think we should serve the gif images without knowing exactly from where they are coming. Maybe it sounds weird but what I am proposing here is exactly to abstract where the images are.  

Currently, we know exactly where they are, because we have on the column `gif_url` the absolute path (including protocol and domain) of where they should be stored: `https://ik.imagekit.io/j4l2m9d7n/360/0001.gif?ik-t=1686076659&ik-s=eca83568d1f62ea9319ffc7c52927f0c0fa71ed5`.

I am proposing that we should create a method that will define where the images are stored.
So, let's suppose we decide to call this method `exercise_gif_url(exercise)`. Now our views only need to pass an exercise to that method and we expect that method decides how to build that URL.

That method in another hand can use a specific logic to build the URL for that exercise gif. For now, we know that if we are in development mode the image could be found locally in the public folder, and for production, we don't know yet, you can leave a TODO comment there.

We can use `seeds.rb` to copy the files from google drive to your local machine, saving them on the public folder as that method expect to find them.

What do you think about that strategy?

Let me know if you need help and what kind of help you need.
Just remember: by default, you produce the code here because it seems to be more productive for you to practice doing stuff yourself. But if you get stuck or you want to see how I would solve something, I can code some stuff myself as well.
Also, we can schedule a pair programming session for 1 or 2 hours in the future if you want.

**Comment by unfazedEgnimadevspace** [comment]
Hello @americodls  

This is a great idea but i have some questions to ask 

1 Any time i try to access the imagekit url i keep getting bandwidth limit exceeded error  

2 I am thinking the exercise_gif_url method should exist in the application helper module, is that right?

3 Are we still going to keep the gif_url column in the exercises table 

4. Will keeping a 244MB folder in our public folder make our application start up time slower ?

 I will start working on it right away.

 Thank you @americodls

**Comment by americodls** [comment]
> 1 Any time i try to access the imagekit url i keep getting bandwidth limit exceeded error

Yeah, me too. That's a problem. We have no control over that API, probably the provided URL contains an identifier to limit users' requests. But you don't need to access that anymore, right?

> 2 I am thinking the exercise_gif_url method should exist in the application helper module, is that right?

It sounds good to me, at least for now. Maybe we find a better way in the future but I think it is good enough having it as a helper.

> 3 Are we still going to keep the gif_url column in the exercises table

No, you can drop that column after you make it useless.

> Will keeping a 244MB folder in our public folder make our application start-up time slower?

Good question. But it won't. The application will not check those files in boot time. So startup time is not affected.
